---
# update gitolte configuration/setup
- name: gitolite setup
  tags: gitolite
  become: true
  become_user: '{{ gitolite_user_name }}'
  when: '{{ not gitolite_fact_initial_checkmode|default(false) }}'
  action: command gitolite setup
  args:
    chdir: '{{ gitolite_user_home }}'
